name: Dependencies

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check for updates
        run: npm outdated
        
      - name: Update dependencies
        run: npm update
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update dependencies"
          title: "chore(deps): update dependencies"
          body: |
            This PR updates the project dependencies to their latest versions.
            
            ### Changes
            - Updated npm dependencies
            - Security patches
            - Bug fixes
            
            ### Security
            - All updates are automatically tested
            - Security vulnerabilities are prioritized
          branch: "deps/update-$(date +%Y%m%d)"
          base: "main"
          delete-branch: true
          labels: "dependencies,automated" 